package Exercicio_06;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marih Bianchini
 */


public class NovoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NovoJFrame
     */
    public NovoJFrame() {
        initComponents();
        new ThreadRelogio(relogio1).start();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(NovoJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        new ThreadRelogio(relogio2).start();
        try {
            Thread.sleep(4000);
        } catch (InterruptedException ex) {
            Logger.getLogger(NovoJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        new ThreadRelogio(relogio3).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        relogio1 = new javax.swing.JLabel();
        relogio2 = new javax.swing.JLabel();
        relogio3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        relogio1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        relogio1.setText("00:00:00");

        relogio2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        relogio2.setText("00:00:00");

        relogio3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        relogio3.setText("00:00:00");

        jButton1.setText("Novo Alarme");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Novo Alarme");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Novo Alarme");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(relogio1))
                    .addComponent(jButton1))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(relogio2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(relogio3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relogio1)
                    .addComponent(relogio2)
                    .addComponent(relogio3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Sem verificacoes (formato correto ou alarme menor que tempo atual)
        String horarioAlarmeString = JOptionPane.showInputDialog("Digite o horario do alarme (hh:mm:ss): ");
        String horarioRelogioString = relogio1.getText();
        
        String buf[] = horarioAlarmeString.split(":");
        Horario horarioAlarme = new Horario(
                Integer.parseInt(buf[0]),
                Integer.parseInt(buf[1]),
                Integer.parseInt(buf[2]));

        String buf2[] = horarioRelogioString.split(":");
        Horario horarioRelogio = new Horario(
                Integer.parseInt(buf2[0]),
                Integer.parseInt(buf2[1]),
                Integer.parseInt(buf2[2]));
        
        new Alarme(horarioRelogio,horarioAlarme).start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String horarioAlarmeString = JOptionPane.showInputDialog("Digite o horario do alarme (hh:mm:ss): ");
        String horarioRelogioString = relogio2.getText();
        
        String buf[] = horarioAlarmeString.split(":");
        Horario horarioAlarme = new Horario(
                Integer.parseInt(buf[0]),
                Integer.parseInt(buf[1]),
                Integer.parseInt(buf[2]));

        String buf2[] = horarioRelogioString.split(":");
        Horario horarioRelogio = new Horario(
                Integer.parseInt(buf2[0]),
                Integer.parseInt(buf2[1]),
                Integer.parseInt(buf2[2]));
        
        new Alarme(horarioRelogio,horarioAlarme).start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String horarioAlarmeString = JOptionPane.showInputDialog("Digite o horario do alarme (hh:mm:ss): ");
        String horarioRelogioString = relogio3.getText();
        
        String buf[] = horarioAlarmeString.split(":");
        Horario horarioAlarme = new Horario(
                Integer.parseInt(buf[0]),
                Integer.parseInt(buf[1]),
                Integer.parseInt(buf[2]));

        String buf2[] = horarioRelogioString.split(":");
        Horario horarioRelogio = new Horario(
                Integer.parseInt(buf2[0]),
                Integer.parseInt(buf2[1]),
                Integer.parseInt(buf2[2]));
        
        new Alarme(horarioRelogio,horarioAlarme).start();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel relogio1;
    private javax.swing.JLabel relogio2;
    private javax.swing.JLabel relogio3;
    // End of variables declaration//GEN-END:variables
}
